import { nanoid } from 'nanoid';

export const OutTeamInfo = [
  {
    id: nanoid(),
    titleCard: 'Тюшняков Алексей',
    subtitle: 'Project Manager',
    telegram: '#telegram',
    internet: '#internet',
    github: '#git',
  },
  {
    id: nanoid(),
    titleCard: 'Ионова Кристина',
    subtitle: 'Project Manager',
    telegram: '#telegram',
    internet: '#internet',
    github: '#git',
  },
  {
    id: nanoid(),
    titleCard: 'Мезенцева Ольга',
    subtitle: 'UX/UI Designer',
    telegram: '#telegram',
    internet: '#internet',
    github: '',
  },
  {
    id: nanoid(),
    titleCard: 'Баранова Екатерина',
    subtitle: 'UX/UI Designer',
    telegram: '#telegram',
    internet: '#internet',
    github: '',
  },
  {
    id: nanoid(),
    titleCard: 'Громыко Мария',
    subtitle: 'Frontend Developer',
    telegram: '#telegram',
    internet: '',
    github: '#git',
  },
  {
    id: nanoid(),
    titleCard: 'Логвин Григорий',
    subtitle: 'Frontend Developer',
    telegram: '#telegram',
    internet: '',
    github: '#git',
  },
  {
    id: nanoid(),
    titleCard: 'Теплостанский Игорь',
    subtitle: 'Frontend Developer',
    telegram: '#telegram',
    internet: '',
    github: '#git',
  },
  {
    id: nanoid(),
    titleCard: 'Крючкова Екатерина',
    subtitle: 'Frontend Developer',
    telegram: '#telegram',
    internet: '',
    github: '#git',
  },
     {
    id: nanoid(),
    titleCard: 'Мингажева Светлана',
    subtitle: 'Frontend Developer',
    telegram: '#telegram',
    internet: '',
    github: '#git',
  },
  {
    id: nanoid(),
    titleCard: 'Коршиков Виталий',
    subtitle: 'Backend Developer',
    telegram: '#telegram',
    internet: '',
    github: '#git',
  },
  {
    id: nanoid(),
    titleCard: 'Ищенко Игорь',
    subtitle: 'Backend Developer',
    telegram: '#telegram',
    internet: '',
    github: '#git',
  },
  {
    id: nanoid(),
    titleCard: 'Качкаев Алексей',
    subtitle: 'Backend Developer',
    telegram: '#telegram',
    internet: '',
    github: '#git',
  },
  {
    id: nanoid(),
    titleCard: 'Андреев Петр',
    subtitle: 'Backend Developer',
    telegram: '#telegram',
    internet: '',
    github: '#git',
  },
  {
    id: nanoid(),
    titleCard: 'Морозов Дмитрий',
    subtitle: 'Backend Developer',
    telegram: '#telegram',
    internet: '',
    github: '#git',
  },
  {
    id: nanoid(),
    titleCard: 'Абдуллина Ксения',
    subtitle: 'QA Engineer',
    telegram: '#telegram',
    internet: '',
    github: '#git',
  },
  {
    id: nanoid(),
    titleCard: 'Кандакова Александра',
    subtitle: 'QA Engineer',
    telegram: '#telegram',
    internet: '',
    github: '#git',
  },
  
];
export const OutTeamInfoLast = [
  {
    id: nanoid(),
    titleCard: 'Исаева Екатерина',
    subtitle: 'QA Engineer',
    telegram: '#telegram',
    internet: '',
    github: '#git',
  },
  {
    id: nanoid(),
    titleCard: 'Краснобородько Наталья',
    subtitle: 'QA Engineer',
    telegram: '#telegram',
    internet: '',
    github: '#git',
  },
  {
    id: nanoid(),
    titleCard: 'Воротников Никита',
    subtitle: 'QA Engineer',
    telegram: '#telegram',
    internet: '',
    github: '#git',
  },
]; 